Function ОписнаиеМетаданныйДляИнициализацииРедактораMonaco() Экспорт
	Return UT_CodeEditorServer.ОписнаиеМетаданныйДляИнициализацииРедактораMonaco();
EndFunction

Function ОписаниеОбъектаМетаданныхКонфигурацииПоИмени(ВидОбъекта, ИмяОбъекта) Экспорт
	Return UT_CodeEditorServer.ОписаниеОбъектаМетаданныхКонфигурацииПоИмени(ВидОбъекта, ИмяОбъекта);	
EndFunction

Function ОписаниеМетаданныхКонфигурации(ВключатьОписаниеРеквизитов = True) Экспорт
	Return UT_CodeEditorServer.ОписаниеМетаданныхКонфигурации(ВключатьОписаниеРеквизитов);
EndFunction

Function СписокМетаданныхПоВиду(ВидМетаданных) Экспорт
	Return UT_CodeEditorServer.СписокМетаданныхПоВиду(ВидМетаданных);
EndFunction

Function СоответствиеСсылочныхТипов() Экспорт
	Return UT_CodeEditorServer.СоответствиеСсылочныхТипов();
EndFunction
