name: Сообщение об ошибке
description: Программа работает не так как ожидали
labels: ["Ошибка"]
title: "[ОШИБКА] <title>"
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание ошибки и шаги для воспроизведения"
      description: "Понятное описание того, что происходит. Последовательность действий для воспроизведения ошибки"
      placeholder: |
        Пример:
        Произошло то-то то-то, вот тут, после того как я сделал вот это

        1. Перейдите в '...'
        2. Нажмите на '....'
        3. Прокрутите вниз до '....'
        4. Появится ошибка
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: "Ожидаемое поведение"
      description: "Чёткое и краткое описание того, что вы ожидали увидеть."
      placeholder: "Пример: Поведение остаётся таким же, как и раньше"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Окружение"
      description: "Скопируйте строку, выдваемую командой инструментов **Инструменты->Информация для техподдержки** "
      placeholder: |
        - Версия платформы: 8.3.....
        - Режим базы данных(файловая/серверная/веб):
        - Конфигурация:
        - Версия конфигурации:
        - ОС:
        - Версия:
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Дополнительная информация"
      description: "Добавьте сюда любую другую информацию о проблеме."
