import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Руководства",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Программный интерфейс",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    {
      type: "category",
      label: "Инструменты",
      items: [{ type: "autogenerated", dirName: "tools" }],
    },
    "external-modules",
  ],
  contributingSidebar: [
    {
      type: "autogenerated",
      dirName: "contributing",
    },
  ],
};

export default sidebars;
