import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Руководства",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "API",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    {
      type: "category",
      label: "Инструменты",
      link: { type: "doc", id: "tools/overview" },
      items: [
        {
          type: "category",
          label: "Разработка",
          items: [
            { type: "autogenerated", dirName: "tools/development-tools" },
          ],
        },
        {
          type: "category",
          label: "Работа с данными",
          items: [{ type: "autogenerated", dirName: "tools/data-tools" }],
        },
        {
          type: "category",
          label: "Администрирование",
          items: [
            {
              type: "autogenerated",
              dirName: "tools/administration-tools",
            },
          ],
        },
        {
          type: "category",
          label: "Обмен",
          items: [{ type: "autogenerated", dirName: "tools/exchange-tools" }],
        },
        {
          type: "category",
          label: "Отладка",
          items: [{ type: "autogenerated", dirName: "tools/debugging-tools" }],
        },
      ],
    },
  ],
  contributingSidebar: [
    {
      type: "autogenerated",
      dirName: "contributing",
    },
  ],
};

export default sidebars;
