name: Сборка файлов поставки для ветки develop основного репозитория
on:
  push:
    branches:
      - "develop"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.repository }}-export
  cancel-in-progress: true

jobs:
  build-dev-version:
    uses: ./.github/workflows/build-version-files.yml
    with:
      tag_name: "v0.0.0"
      prerelease: true
